### ISSUE TITLE
GardenFiles23

### ISSUE THREAD

**Issue by aharmax** [bioacoustic-ai/bioacoustics-datasets#27]
Hi, I apparently have no permission to add a json. I have attached the filled form to this issue. 

[GardenFiles23.json](https://github.com/user-attachments/files/17585969/GardenFiles23.json)

Best regards, Aki

**Comment by Cangonin** [comment]
Yes, you don't have the write permission, so you are not allowed to push changes to this repo. People don't have this permission by default for security reasons. The way to contribute is then to fork this repository, create a branch there, apply your changes, and open a pull request to this repo from the fork. Tell me if you know an easier workflow with Github to let people collaborate.

I propose that I add the json file myself to the repository. Does that sound good or do you prefer to create a fork and open the pull request yourself ?

**Comment by Cangonin** [comment]
I added the file myself. Thank you for providing the file! I will now close this issue
