### ISSUE TITLE
New underwater reef sound dataset

### ISSUE THREAD

**Issue by cparcerisas** [bioacoustic-ai/bioacoustics-datasets#30]
https://zenodo.org/records/11071202
To be added? 

Thank you!

**Comment by Cangonin** [comment]
This dataset is already present! I guess that you opened the list and couldn't find it. That's slightly concerning to me, because I would like the list of datasets to be easy to navigate. If you have feedback on what could be improved, that would be great!

**Comment by Cangonin** [comment]
I see! I could specify all taxonomic groups instead of writing "Mixed" for the taxonomic class in case one dataset contains several of them. Thank you for proposing this dataset, and don't hesitate to open another issue if you encounter a dataset that is not present in the list!
